name: Default ci pipeline

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20.16.0'

            - name: Install deps
              run: npm ci

            - name: Run lint and format
              run: |
                  npm run lint
                  npm run format

            - name: Run unit tests
              run: npm run test
